# Generated by Django 5.1.15 on 2026-06-24 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0002_abwesenheit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Betriebszugehoerigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('betrieb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitglieder', to='planning.betrieb', verbose_name='Betrieb')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zugehoerigkeit', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Betriebszugehörigkeit',
                'verbose_name_plural': 'Betriebszugehörigkeiten',
            },
        ),
    ]
