# Generated by Django 5.1.15 on 2026-06-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Betrieb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Betrieb',
                'verbose_name_plural': 'Betriebe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Abteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('betrieb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abteilungen', to='planning.betrieb', verbose_name='Betrieb')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=80, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=80, verbose_name='Nachname')),
                ('rolle', models.CharField(blank=True, max_length=80, verbose_name='Rolle')),
                ('vertragsstunden', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Vertragsstunden/Woche')),
                ('farbe', models.CharField(default='#2563eb', max_length=7, verbose_name='Farbe')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('abteilung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitarbeiter', to='planning.abteilung', verbose_name='Abteilung')),
                ('betrieb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeiter', to='planning.betrieb', verbose_name='Betrieb')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Schichtvorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('beginn', models.TimeField(verbose_name='Beginn')),
                ('ende', models.TimeField(verbose_name='Ende')),
                ('benoetigte_rolle', models.CharField(blank=True, max_length=80, verbose_name='Benötigte Rolle')),
                ('farbe', models.CharField(default='#2563eb', max_length=7, verbose_name='Farbe')),
                ('abteilung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schichtvorlagen', to='planning.abteilung', verbose_name='Abteilung')),
                ('betrieb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichtvorlagen', to='planning.betrieb', verbose_name='Betrieb')),
            ],
            options={
                'verbose_name': 'Schichtvorlage',
                'verbose_name_plural': 'Schichtvorlagen',
                'ordering': ['beginn', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schicht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('bedarf', models.PositiveSmallIntegerField(default=1, verbose_name='Benötigte Mitarbeiter')),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichten', to='planning.schichtvorlage', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Schicht',
                'verbose_name_plural': 'Schichten',
                'ordering': ['datum', 'vorlage__beginn'],
            },
        ),
        migrations.CreateModel(
            name='Zuweisung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zuweisungen', to='planning.mitarbeiter', verbose_name='Mitarbeiter')),
                ('schicht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zuweisungen', to='planning.schicht', verbose_name='Schicht')),
            ],
            options={
                'verbose_name': 'Zuweisung',
                'verbose_name_plural': 'Zuweisungen',
                'ordering': ['schicht__datum'],
            },
        ),
        migrations.AddConstraint(
            model_name='abteilung',
            constraint=models.UniqueConstraint(fields=('betrieb', 'name'), name='abteilung_name_je_betrieb_eindeutig'),
        ),
        migrations.AddConstraint(
            model_name='schicht',
            constraint=models.UniqueConstraint(fields=('vorlage', 'datum'), name='schicht_je_vorlage_und_datum_eindeutig'),
        ),
        migrations.AddConstraint(
            model_name='zuweisung',
            constraint=models.UniqueConstraint(fields=('schicht', 'mitarbeiter'), name='mitarbeiter_je_schicht_eindeutig'),
        ),
    ]
