# Generated by Django 5.1.15 on 2026-06-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abwesenheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('urlaub', 'Urlaub'), ('krank', 'Krank'), ('sonstiges', 'Sonstiges')], default='urlaub', max_length=20, verbose_name='Art')),
                ('von', models.DateField(verbose_name='Von')),
                ('bis', models.DateField(verbose_name='Bis')),
                ('notiz', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abwesenheiten', to='planning.mitarbeiter', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Abwesenheit',
                'verbose_name_plural': 'Abwesenheiten',
                'ordering': ['-von'],
                'constraints': [models.CheckConstraint(condition=models.Q(('bis__gte', models.F('von'))), name='abwesenheit_bis_nicht_vor_von')],
            },
        ),
    ]
